### ISSUE TITLE
API Version Grouping Based on API Identifier

### ISSUE THREAD

**Issue by boberhauser** [TNG/ApiCenter#16]
We are using UUIDs as API identifiers as suggested by the Zalando API guidelines (https://opensource.zalando.com/restful-api-guidelines/#215). We would like to group APIs based on this identifier (currently no identifier is supported and every submitted API spec leads to a new API created, even on version updates). We will create a pull request if you also support this idea.

**Comment by fdw** [comment]
I think that makes a lot of sense, yes :)

However, as @alexkaserbacher mentioned offline, the field should be optional, as we cannot expect everyone to adhere to Zalando's guidelines.

**Comment by boberhauser** [comment]
I agree, it should be optional. We will have a look and come back with a proposal as pull-request.

**Comment by fdw** [comment]
For the protocol: We had a short discussion about how this ID should be handled when adding new versions in PR #25: ID takes precedence over name, so that two services with different IDs can have the same name.
