### ISSUE TITLE
Global Search Function

### ISSUE THREAD

**Issue by alexkaserbacher** [TNG/ApiCenter#3]
A global search function should be implemented, providing a search over all metadata and all contents of specification files.

A search-bar should be displayed in the header-bar and search results should show up as a pop-down list when the search term is entered.

**Comment by fdw** [comment]
As we discussed offline, there are probably different kinds of searching behavior:
- "Which service can give me that data?"
- "Can one of the services I use already do that?"
- "Which method do I need to use?"
- "Give me the documentation for this exact method."

Note that the last one is vastly different than the other three.
