### ISSUE TITLE
Permission Management

### ISSUE THREAD

**Issue by alexkaserbacher** [TNG/ApiCenter#5]
Users should be able to give permissions on specifications they've created. There should be three permission levels:
* view - the user can view the specification
* edit - the user can edit the specification
* admin - the user can give permissions for the specification

Permission settings should be possible by clicking on an icon within the icon bar in the specification overview.

**Comment by fdw** [comment]
I think there could be more levels (possibly even unrelated "rights"), like the ability to upload a pre-release version or to publish a version.

**Comment by fdw** [comment]
One more thing: As soon as basic rights are implemented, logging in shoud not be required anymore.
