### ISSUE TITLE
Change phrasing

### ISSUE THREAD

**Issue by fdw** [TNG/ApiCenter#54]
Instead of a "specification" having "versions", it should rather be a "service" having "specifications" (which might differ in their "version" or "language"). As a user, I can better understand these terms because they are more intuitive.

**Comment by catenoid** [comment]
This does slightly conflate with Spring's "@Service" annotation, ie. we end up with 'ServiceFileService' / 'ServiceDataService'

**Comment by fdw** [comment]
To be honest, I don't like the names of these classes: They don't say anything about the class' responsibility. One is probably a `SpecificationDataParser` and the other a `SpecificationFileDownloader`. Since they deal with spec files, they should also keep the word in the name.

Finally,  the `SynchronizationService` should be something like a `RemoteSpecificationUpdater`.

**Comment by catenoid** [comment]
One misgiving I have here is how it interferes with the `/specification/{specificationId}/version/{version}` pattern.

**Comment by fdw** [comment]
That's right. Maybe `/service/{serviceId}/version/{version}`? I think that captures the idea quite well, and since we don't expose the version string as a resource, this is also unambiguous.
