### ISSUE TITLE
Order specifications semantically rather than by upload date

### ISSUE THREAD

**Issue by catenoid** [TNG/ApiCenter#66]
The solution [here](https://dba.stackexchange.com/questions/74283/how-to-order-by-typical-software-release-versions-like-x-y-z) may prove helpful (though ApiCenter's SQL dialect doesn't support PostgreSQL `string_to_array`)

**Comment by fdw** [comment]
Would it make sense to force a certain versioning scheme (i.e. SemVer)?

**Comment by catenoid** [comment]
I think so, yes, I don't see how we can reliably order versions without. Especially considering ApiCenter will possibly in future track dependencies between versions.
